apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  storageClassName: datos
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
