apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
spec:
  storageClassName: datos
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/datos/wordpress"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db
spec:
  storageClassName: datos
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/datos/db"
