apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: datos
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/datos/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  storageClassName: datos
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/datos/pv2"
