apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  storageClassName: datos
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
